### ISSUE TITLE
models.DecimalField no longer supported?

### ISSUE THREAD

**Issue by giilby** [algolia/algoliasearch-django#340]
Maybe this is actually an issue with a newer version of https://github.com/algolia/algoliasearch-client-python, but in any case, after upgrading to v4.0.0 of this package + v4.13.0 of the python client, indexing models with `models.DecimalField` fields fails with this error:

`AttributeError: 'decimal.Decimal' object has no attribute 'to_dict'`

**Comment by Enase** [comment]
same here, would be great to add:
```
    elif isinstance(obj, Decimal):
        return float(obj)
```
here https://github.com/algolia/algoliasearch-client-python/blob/main/algoliasearch/http/serializer.py#L64

**Comment by shortcuts** [comment]
Thanks! I'll release asap :)
